# Generated by Django 3.0.8 on 2020-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('index_bd', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='index_bd')),
                ('cor', models.CharField(blank=True, max_length=10, verbose_name='valor')),
                ('valor', models.FloatField(blank=True, default=0, verbose_name='valor')),
                ('data_hora', models.DateTimeField(verbose_name='data_hora')),
            ],
            options={
                'db_table': 'Tabela_MyProject',
                'unique_together': {('cor', 'data_hora')},
            },
        ),
    ]
