# Generated by Django 2.2.8 on 2020-04-04 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_character', models.CharField(blank=True, max_length=100, verbose_name='Character')),
                ('app_integer', models.IntegerField(blank=True, default=1, verbose_name='Integer')),
                ('app_float', models.FloatField(blank=True, default=0.5, verbose_name='Float')),
                ('app_boolean', models.BooleanField(blank=True, default=False, verbose_name='Boolean')),
                ('app_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Data de aprovação FEL1')),
                ('app_date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 36, 57, 98222), verbose_name='TimeStamp')),
            ],
        ),
    ]
