# Generated by Django 2.2.8 on 2020-04-04 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_auto_20200404_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='App2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_character', models.CharField(blank=True, max_length=100, verbose_name='Character')),
                ('app_integer', models.IntegerField(blank=True, default=1, verbose_name='Integer')),
                ('app_float', models.FloatField(blank=True, default=0.5, verbose_name='Float')),
                ('app_boolean', models.BooleanField(blank=True, default=False, verbose_name='Boolean')),
                ('app_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Data de aprovação FEL1')),
                ('app_date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 22, 2, 20, 802342, tzinfo=utc), verbose_name='TimeStamp')),
            ],
        ),
        migrations.CreateModel(
            name='App3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_character', models.CharField(blank=True, max_length=100, verbose_name='Character')),
                ('app_integer', models.IntegerField(blank=True, default=1, verbose_name='Integer')),
                ('app_float', models.FloatField(blank=True, default=0.5, verbose_name='Float')),
                ('app_boolean', models.BooleanField(blank=True, default=False, verbose_name='Boolean')),
                ('app_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Data de aprovação FEL1')),
                ('app_date_time', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 22, 2, 20, 803316, tzinfo=utc), verbose_name='TimeStamp')),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 22, 2, 20, 725294, tzinfo=utc), verbose_name='TimeStamp'),
        ),
    ]
