# Generated by Django 2.2.8 on 2020-04-05 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_auto_20200404_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 1, 27, 56, 106923, tzinfo=utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='app2',
            name='app_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='app2',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 1, 27, 56, 137180, tzinfo=utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='app3',
            name='app_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='app3',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 1, 27, 56, 137180, tzinfo=utc), verbose_name='DateTime'),
        ),
    ]
